import { StyleSheet } from 'react-native';
import { Colors } from '../../../../constant';
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from '../../../../constant/dimentions';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f7f9f6' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#eef1eb',
  },
  backBtn: { padding: 6, marginRight: 10 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#000' },
  mapWrapper: { height: 220, backgroundColor: '#dfe8d8' },
  mapImage: { width: '100%', height: '100%' },
  section: {
    backgroundColor: '#fff',
    marginHorizontal: wp(4),
    marginTop: hp(2),
    borderRadius: 12,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#000', marginBottom: 8 },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: '#f0f2ec',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#cdd8c5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxFill: {
    width: 12,
    height: 12,
    borderRadius: 4,
    backgroundColor: Colors.PRIMARY[300],
  },
  productImg: { width: 52, height: 52, borderRadius: 10, marginRight: 10, backgroundColor: '#f2f2f2' },
  productInfo: { flex: 1 },
  productName: { color: '#000', fontWeight: '700' },
  variantText: { color: '#666', fontSize: 12, marginTop: 2 },
  priceRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  price: { color: '#000', fontWeight: '700', marginRight: 6 },
  oldPrice: { color: '#888', textDecorationLine: 'line-through', fontSize: 12 },
  qtyBadge: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#eef3e8',
  },
  qtyText: { color: '#000', fontWeight: '700', fontSize: 12 },
  inlineRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  tag: { paddingHorizontal: 10, paddingVertical: 6, backgroundColor: '#eef3e8', borderRadius: 10 },
  tagText: { color: '#1B743E', fontWeight: '700', fontSize: 12 },
  textInput: {
    borderWidth: 1,
    borderColor: '#e2e8dd',
    borderRadius: 10,
    padding: 10,
    marginTop: 8,
    backgroundColor: '#fafcf7',
    color: '#000',
  },
  billRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6 },
  divider: { height: 1, backgroundColor: '#edf1ea', marginVertical: 8 },
  addressBlock: { marginTop: 4 },
  addressText: { color: '#444', marginTop: 2 },
  footer: { paddingHorizontal: wp(4), paddingVertical: 16, backgroundColor: '#fff', borderTopWidth: 1, borderColor: '#eef1eb' },
  primaryBtn: {
    backgroundColor: Colors.PRIMARY[300],
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  disabledBtn: {
    backgroundColor: '#c7d0c3',
  },
  btnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  badgeInfo: {
    marginTop: 8,
    backgroundColor: '#eef7e9',
    padding: 10,
    borderRadius: 10,
  },
  warning: { color: '#d17300', marginTop: 6, fontWeight: '700' },
  tinyLabel: { fontSize: 12, color: '#777' },
});



