import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from '../../../../constant/dimentions';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: hp(2.5),
    fontWeight: '700',
    color: '#000',
  },
  scrollContent: {
    padding: wp(4),
    paddingBottom: 100,
  },
  itemsCount: {
    fontSize: hp(2),
    fontWeight: '700',
    color: '#000',
    marginBottom: hp(2),
  },
  productCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8F5E9',
    padding: wp(4),
    marginBottom: hp(2),
  },
  productImage: {
    width: wp(20),
    height: wp(20),
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
  },
  productInfo: {
    flex: 1,
    marginLeft: wp(3),
  },
  productHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  productName: {
    fontSize: hp(2),
    fontWeight: '700',
    color: '#000',
    flex: 1,
  },
  editBadge: {
    backgroundColor: '#FF9800',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    borderRadius: 4,
    marginLeft: wp(2),
  },
  editBadgeText: {
    color: '#fff',
    fontSize: hp(1.4),
    fontWeight: '600',
  },
  productQuantity: {
    fontSize: hp(1.6),
    color: '#666',
    marginBottom: 8,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  price: {
    fontSize: hp(2),
    fontWeight: '700',
    color: '#4CAF50',
  },
  mrp: {
    fontSize: hp(1.6),
    color: '#999',
    textDecorationLine: 'line-through',
    marginLeft: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: hp(1.5),
  },
  starButton: {
    padding: 4,
  },
  reviewInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: wp(3),
    fontSize: hp(1.8),
    color: '#000',
    backgroundColor: '#FAFAFA',
    minHeight: hp(8),
    marginTop: hp(1),
  },
  submitContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderTopWidth: 1,
    borderTopColor: '#eee',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  submitButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 12,
    paddingVertical: hp(2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: hp(2.2),
    fontWeight: '700',
  },
  // Styled Alert Modal Styles
  alertOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
  },
  alertContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: wp(6),
    width: '100%',
    maxWidth: wp(85),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  alertIconContainer: {
    width: wp(20),
    height: wp(20),
    borderRadius: wp(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  alertIconSuccess: {
    backgroundColor: '#4CAF50',
  },
  alertIconError: {
    backgroundColor: '#F44336',
  },
  alertIconInfo: {
    backgroundColor: '#2196F3',
  },
  alertTitle: {
    fontSize: hp(2.5),
    fontWeight: '700',
    color: '#000',
    marginBottom: hp(1),
    textAlign: 'center',
  },
  alertMessage: {
    fontSize: hp(1.9),
    color: '#666',
    textAlign: 'center',
    marginBottom: hp(3),
    lineHeight: hp(2.8),
  },
  alertButton: {
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(10),
    borderRadius: 12,
    minWidth: wp(30),
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertButtonSuccess: {
    backgroundColor: '#4CAF50',
  },
  alertButtonError: {
    backgroundColor: '#F44336',
  },
  alertButtonInfo: {
    backgroundColor: '#2196F3',
  },
  alertButtonText: {
    color: '#fff',
    fontSize: hp(2),
    fontWeight: '700',
  },
});
